# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.picButton = QtWidgets.QPushButton(self.centralwidget)
        self.picButton.setGeometry(QtCore.QRect(40, 100, 100, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.picButton.setFont(font)
        self.picButton.setObjectName("picButton")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(150, 20, 500, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.title.setFont(font)
        self.title.setToolTipDuration(-1)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.vidButton = QtWidgets.QPushButton(self.centralwidget)
        self.vidButton.setGeometry(QtCore.QRect(40, 180, 100, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.vidButton.setFont(font)
        self.vidButton.setObjectName("vidButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 100, 560, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 180, 560, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.picButton.setText(_translate("MainWindow", "图片识别"))
        self.title.setText(_translate("MainWindow", "基于卷积神经网络的手势识别系统"))
        self.vidButton.setText(_translate("MainWindow", "视频识别"))
        self.label.setText(_translate("MainWindow", "使用导入的图片测试模型"))
        self.label_2.setText(_translate("MainWindow", "使用摄像头，实时测试模型"))
