# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'picture_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(240, 420)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.showCase = QtWidgets.QLabel(self.centralwidget)
        self.showCase.setGeometry(QtCore.QRect(20, 20, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.showCase.setFont(font)
        self.showCase.setAlignment(QtCore.Qt.AlignCenter)
        self.showCase.setObjectName("showCase")
        self.recButton = QtWidgets.QPushButton(self.centralwidget)
        self.recButton.setGeometry(QtCore.QRect(70, 300, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.recButton.setFont(font)
        self.recButton.setObjectName("recButton")
        self.returnButton = QtWidgets.QPushButton(self.centralwidget)
        self.returnButton.setGeometry(QtCore.QRect(70, 350, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.returnButton.setFont(font)
        self.returnButton.setObjectName("returnButton")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 80, 200, 200))
        self.listWidget.setObjectName("listWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.showCase.setText(_translate("MainWindow", "sample name"))
        self.recButton.setText(_translate("MainWindow", "识别"))
        self.returnButton.setText(_translate("MainWindow", "返回"))
